# Generated by Django 3.0.5 on 2021-10-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_patien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patien',
            name='id',
        ),
        migrations.AlterField(
            model_name='patien',
            name='PatId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
