# Generated by Django 3.0.5 on 2021-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211007_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patien',
            name='PatNais',
            field=models.DateField(blank=True, null=True),
        ),
    ]
