# Generated by Django 3.1.7 on 2022-05-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('Tweet', models.TextField()),
                ('Retweet', models.BigIntegerField()),
                ('Cluster', models.BigIntegerField()),
            ],
        ),
    ]
